### ISSUE TITLE
Issue clickable area

### ISSUE THREAD

**Issue by Jono20201** [jakewtaylor/git-dash#11]
Would potentially be nice for the area to open the PR was the entire of the card instead of just the title.

**Comment by jakewtaylor** [comment]
As in a screen that lets you see the entire PR? I did think about that but I don't want to get carried away and recreate the entire GitHub PR UI 😆 Or do you mean something else?

**Comment by Jono20201** [comment]
No, I mean to extend the clickable area so instead of just clicking the title to open the PR I could click anywhere in the card?

![image](https://user-images.githubusercontent.com/2374192/75339468-8053e600-5888-11ea-858c-eaa969067ead.png)

**Comment by jakewtaylor** [comment]
Oooh I see haha. That should be easy enough to do

**Comment by jakewtaylor** [comment]
Although there are other clickable items in the card so not sure if that will work correctly?

**Comment by jakewtaylor** [comment]
Made a bit of an adjustment in 0e45f60
made the clickable area a bit bigger but still around the title, you don't have to be quite as precise
