### ISSUE TITLE
Add ability to collapse/expand the repository selector at the top of the page

### ISSUE THREAD

**Issue by mbrookson** [jakewtaylor/git-dash#12]
Once you've selected repos you want to see, it's unlikely you want to change it often.

Would be good if the selector could collapse so it's out of the way when not in use. 

![image](https://user-images.githubusercontent.com/20131783/75799403-f4eac100-5d6f-11ea-932d-5195405fb127.png)

**Comment by mbrookson** [comment]
This has been resolve 🙂

**Comment by jakewtaylor** [comment]
> This has been resolve 🙂

by #13
