### ISSUE TITLE
Show more repositories

### ISSUE THREAD

**Issue by mbrookson** [jakewtaylor/git-dash#14]
When you have a lot of repositories available in your account you are unable to see them all due to the query being used. Therefore some people cannot select the repos they want to see.

Would be good to add paging, or even be more clever about which repos are shown; perhaps order by last committed to for example?

The 'pill' style selector might need rethinking to improve the UX of selecting repos when there are a lot to choose from.

**Comment by jakewtaylor** [comment]
Was thinking of leaving the 'top repositories' bit, but with an extra area to manually add a specific repo either by typing in the 'owner/name' string or by selecting from a complete list of the users repos.

**Comment by Jono20201** [comment]
Encountering this issue also.

**Comment by mbrookson** [comment]
@jakewtaylor How would you work out which are the 'top repositories'?

**Comment by jakewtaylor** [comment]
@mbrookson I believe it’s just the latest _x_ repos by activity, just what is returned from GitHub’s graphql api
