### ISSUE TITLE
Show the source and target branches for a PR

### ISSUE THREAD

**Issue by mbrookson** [jakewtaylor/git-dash#16]
It would be useful to show the source and target branches, with an arrow indicating the merge direction for a PR (similar to how GitHub does).

This is particularly useful when you have the same named PR for a hotfix, which has been PRd into both master and develop.

Mocked up this as a suggestion.

![image](https://user-images.githubusercontent.com/20131783/79992796-e1282500-84ab-11ea-8c18-51522a08edbd.png)

**Comment by jakewtaylor** [comment]
Added in e52eb9d 😄
