### ISSUE TITLE
Show whether a PR is a draft

### ISSUE THREAD

**Issue by mbrookson** [jakewtaylor/git-dash#17]
Often draft PRs do not require properly reviewing yet, so it would be nice be able to tell if a PR is a draft vs ready to review.

**Comment by mbrookson** [comment]
Thanks @jakewtaylor !

**Comment by jakewtaylor** [comment]
Thank @Jono20201, not me!

**Comment by mbrookson** [comment]
Oh! 😂  Thanks @Jono20201!
